project:
  type: website

website:
  title: "Mokhtar Tabari"
  site-url: "https://www.mokhtartabari.ca/"
  google-analytics: "UA-149903273-1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Presentations
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
