project:
  type: website

website:
  title: "Mokhtar Tabari"
  site-url: "https://mokhtartabari.github.io/"
  google-analytics: "UA-149903273-1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Presentations
      - href: posts/
        text: Blog
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    appearance: auto
    html-theme-provider: bootswatch
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
          <style>
          /* FORCE BLACK TEXT in LIGHT MODE only */
          @media (prefers-color-scheme: light) {
            body, p, li, div, span, h1, h2, h3, h4, h5, h6 {
              color: #000000 !important;
            }
            .position, .affiliation {
              color: #000000 !important;
            }
          }
          /* Ensure DARK MODE has light text */
          @media (prefers-color-scheme: dark) {
            body, p, li, div, span, h1, h2, h3, h4, h5, h6 {
              color: #e9ecef !important;
            }
            .position, .affiliation {
              color: #e9ecef !important;
            }
          }
          </style>
