project:
  type: website

website:
  title: "Mokhtar Tabari"
  site-url: "https://www.mokhtartabari.ca/"
  google-analytics: "UA-149903273-1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Presentations
      - href: posts/
        text: Blog
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    appearance: auto
    html-theme-provider: default
